common: &common
  adapter: postgresql
  username: root
  password:  # from psql setup, see Postgresql

development:
  <<: *common
  database: sample_development

test:
  <<: *common
  database: sample_test

production:
  <<: *common
  database: sample_app